---
- name: configure for ldap | ensure LDAP longin module configuration exists
  template:
    dest: "{{ rundeck_conf_dir }}/jaas-ldap.conf"
    src: jaas-ldap.conf.j2
    owner: "{{ rundeck_user }}"
    group: "{{ rundeck_group }}"
    mode: 0640

- name: configure for ldap | ensure profile is updated to use LDAP configuration
  lineinfile:
    dest: "{{ rundeck_conf_dir }}/profile"
    regexp: '^export RDECK_JVM(.*)$'
    line: "export RDECK_JVM=\"-Djava.security.auth.login.config={{ rundeck_conf_dir }}/jaas-ldap.conf \\"
  when: ansible_os_family == 'Debian'
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - ldap

- name: configure for ldap | ensure /etc/sysconfig/rundeckd exists
  file:
    path: /etc/sysconfig/rundeckd
    state: touch
  when: ansible_os_family == 'RedHat'
  tags:
    - rundeck
    - configuration
    - ldap

- name: configure for ldap | ensure jaas conf exists in /etc/sysconfig/rundeckd
  lineinfile:
    path: /etc/sysconfig/rundeckd
    line: "JAAS_CONF={{ rundeck_conf_dir }}/jaas-ldap.conf"
  when: ansible_os_family == 'RedHat'
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - ldap

- name: configure for ldap | ensure profile is updated to use LDAP module
  lineinfile:
    dest: "{{ rundeck_conf_dir }}/profile"
    regexp: '^(\s*)-Dloginmodule.name=(.*)$'
    line: '        -Dloginmodule.name=ldap \'
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - ldap
