---
# Redhat based OS
- name: Redhat | get rundeck rpm
  yum:
    name: http://repo.rundeck.org/latest.rpm
    state: present
  become: yes
  tags:
    - rundeck
    - install
    - packages

- name: Redhat | get rundeck rpm
  yum:
    name: rundeck
    state: present
  become: yes
  notify:
    - start rundeck
  tags:
    - rundeck
    - install
    - packages

- name: discover version number
  shell: yum info rundeck | grep -i version | grep -o '[0-9.]\+'
  register: rundeck_targeting_version
