---
# Redhat based OS
- name: Redhat | get rundeck rpm
  yum:
    name: http://repo.rundeck.org/latest.rpm
    state: present
  become: yes
  tags:
    - rundeck
    - install
    - packages

- name: Redhat | get rundeck rpm
  yum:
    name: rundeck
    state: present
  become: yes
  notify:
    - start rundeck
  tags:
    - rundeck
    - install
    - packages

- name: Redhat | add systemd service helper
  copy:
    src: systemd/rundeck-start
    dest: /usr/bin/rundeck-start
    owner: root
    group: root
    mode: 0755
  when: ansible_service_mgr == 'systemd'
  tags:
    - rundeck
    - install
    - packages

- name: Redhat | add systemd service unit
  copy:
    src: systemd/rundeckd.service
    dest: /etc/systemd/system/rundeckd.service
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'
  notify:
    - systemd daemon-reload
  tags:
    - rundeck
    - install
    - packages

- name: Redhat | ensure service log directory has correct ownership
  file:
    path: /var/log/rundeck
    owner: rundeck
    state: directory
  tags:
    - rundeck
    - install
    - packages

- name: Redhat | See if there are more log files
  find:
    paths: /var/log/rundeck
    file_type: file
    patterns: "*.log"
  register: rundeck_logfiles
  tags:
    - rundeck
    - install
    - packages

- name: Redhat | ensure service log files have correct ownership
  file:
    path: "{{ item.path }}"
    owner: rundeck
    state: file
  with_items:
    "{{ rundeck_logfiles.files|default([]) }}"
  tags:
    - rundeck
    - install
    - packages

- name: set rundeck_package_command for redhat
  set_fact:
    rundeck_package_command: yum info
