---
- name: make server lib directory
  file:
    group=rundeck
    mode=0655
    owner=rundeck
    path=/var/lib/rundeck/lib
    state=directory
  tags:
    - rundeck
    - directory
    - postgresql

- name: download postgreSQL jdbc driver
  get_url:
    dest=/var/lib/rundeck/lib/postgresql-9.3-1101.jdbc3.jar
    url="http://jdbc.postgresql.org/download/postgresql-9.3-1101.jdbc3.jar"
    group=rundeck
    mode=0655
    owner=rundeck
  tags:
    - rundeck
    - jdbc
    - postgresql

- name: adjust main configuration
  lineinfile:
    dest=/etc/rundeck/rundeck-config.properties
    regexp="^dataSource.url"
    line="dataSource.url=jdbc:postgresql://{{ rundeck_database_host }}:{{ rundeck_database_port}}/rundeck"
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - postgresql
